### ISSUE TITLE
non-minified version of the source code?

### ISSUE THREAD

**Issue by robertocabellon** [lrusso/3DObjectViewer#2]
Excelelent work!! Would you mind sharing the non-minified version of the javascript source code? Thanks!

**Comment by lrusso** [comment]
Roberto,

Thank you very much for your message and interest in 3D Object Viewer. The minified code in https://github.com/lrusso/3DObjectViewer/blob/master/3DObjectViewer.js is actually several files from the Three.js project (https://threejs.org/). On the other hand, the source code related to the project (https://github.com/lrusso/3DObjectViewer/blob/master/3DObjectViewer.htm) is not minified.

Best regards,
Leonardo
