### ISSUE TITLE
Issue in loading multiple files and not able to change the position of choose file.

### ISSUE THREAD

**Issue by aarya1906** [lrusso/3DObjectViewer#3]

**Comment by lrusso** [comment]
The App/Web wasn't designed for several files/meshes. If so, you must use the same logic to each model file.

**Comment by aarya1906** [comment]
How to resize the page?

I tried out decreasing the width in css but nothing works.

**Comment by lrusso** [comment]
https://github.com/lrusso/3DObjectViewer/blob/master/3DObjectViewer.htm#L314

Please check the three.js documentation for other related issues.

**Comment by aarya1906** [comment]
Thank you for the help
